# Generated by Django 5.1.7 on 2025-03-19 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('person_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Lives',
            fields=[
                ('person_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='employee.works')),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
